ID-142 Fix triple vertical scroll bars on beacon
DNAstack/ddap-explore pull request #25
Opened 2020-05-14 21:11 UTC by andrewlor

Screenshots from different browsers (with macOS preference to always show scrollbars):
![Screen Shot 2020-05-14 at 3 01 16 PM](https://user-images.githubusercontent.com/8475244/81986309-cc473900-95f4-11ea-89c0-05dd6c084327.png)
![Screen Shot 2020-05-14 at 3 01 29 PM](https://user-images.githubusercontent.com/8475244/81986312-ce10fc80-95f4-11ea-8c61-a3dcc31e3ff9.png)
![Screen Shot 2020-05-14 at 3 02 06 PM](https://user-images.githubusercontent.com/8475244/81986317-cf422980-95f4-11ea-8b20-8860f622f216.png)

2020-05-15 18:49 UTC, shiroyuki requested changes

2020-05-15 18:49 UTC, shiroyuki commented on angular/src/app/discovery/beacon/beacon-search-result-table/beacon-search-result-table.component.scss
> +  overflow: auto;
Please stick with `overflow-y`. This change tells the browser to create a scrollbar for any axis if needed.

2020-05-15 18:49 UTC, shiroyuki commented on angular/src/app/discovery/beacon/beacon-search.component.scss
> +  overflow: auto;
Same as the comment above.

2020-05-15 18:49 UTC, shiroyuki commented on angular/src/app/discovery/beacon/beacon-search.component.scss
> +  overflow: auto;
Same as the comment above.

2020-05-18 09:49 UTC, mpanik approved these changes

2020-05-18 09:50 UTC, merged