Id 135
DNAstack/ddap-explore pull request #26
Opened 2020-05-15 17:34 UTC by JennaBarbara

2020-05-19 15:56 UTC, shiroyuki requested changes

2020-05-19 15:56 UTC, shiroyuki commented on angular/src/app/shared/data-table/data-table.component.html
> +<div style="align-self: flex-end;">
Please see "semantic CSS" in https://docs.google.com/document/d/1fQz5u6oM56qZ2hinDvPklexG6qvnu-jcymdhU5NblVQ/edit

2020-05-19 15:56 UTC, shiroyuki commented on angular/src/app/shared/data-table/data-table.component.html
> +  </button>
1. According to the design, it is an icon button (`mat-icon-button`).
2. The name of the icon in question should be found in https://material.io/resources/icons/?style=baseline.

2020-05-19 15:56 UTC, shiroyuki commented on angular/src/app/shared/data-table/data-table.component.ts
> +  }
Can you merge this with `onBenExportDataAsCsv`?

2020-05-19 16:10 UTC, mpanik commented on angular/src/app/shared/data-table/data-table.component.html
> +  <button (click)="onBtnExportDataAsCsv()" mat-stroked-button color="accent">
should be just named `exportDataAsCsv()`

2020-05-22 10:22 UTC, mpanik commented
Superseded by https://github.com/DNAstack/ddap-explore/pull/31

2020-05-22 10:22 UTC, closed without merging